#! /bin/bash

set -o errexit  # the script ends if a command fails
set -o pipefail # the script ends if a command fails in a pipe
set -o nounset  # the script ends if it uses an undeclared variable

# script que retorna 
#     un SI si el primer parámetro coincide con algún usuario conectado
#     un NO en caso contrario

function ayuda() {

cat << DESCRIPCION_AYUDA
SYNOPSIS
    $0 NOMBRE_USUARIO

DESCRIPCION
   Devuelve:
       SI si NOMBRE_USUARIO coincide con algún usuario conectado o
       NO si NOMBRE_USUARIO no coincide con ningún usuario conectado

CÓDIGOS DE RETORNO
    1 Si el número de parámetros es distinto de 1
DESCRIPCION_AYUDA

}

# si número de parámetros distinto 1
if [ $# -ne 1 ]; then
    echo "El número de parámetros debe de igual a 1"
    ayuda
    exit 1
fi

who | grep -E "^$1 .+$" > /dev/null && echo "SI" || echo "NO"
