#! /bin/bash

set -o errexit  # the script ends if a command fails
set -o pipefail # the script ends if a command fails in a pipe
set -o nounset  # the script ends if it uses an undeclared variable

# si el número de parámetros es distinto de 0
if [ "$#" != "0" ]; then

	# muestra un mensaje de error y sale
	echo "No se permiten parámetros."
	exit 1
fi

# muestra el listado ordenado de menor a mayor por el tamaño
# sacando sólo el nombre del archivo y el número de línea
ls -l | sort -nk 5 | awk '{ print $8 }' | nl
